### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by NirvanaFY** [ZZUTK/Face-Aging-CAAE#17]
I use this code to test 
$ python main.py --is_train False --testdir your_image_dir
but the result is as follows:
![image](https://user-images.githubusercontent.com/13418210/31280386-bf942f32-aade-11e7-94d0-93c74d5d93ad.png)
my test image has the same format as UTKFace, and can you tell me how to solve this problem

**Comment by susanqq** [comment]
Because of the display setup in custom testing, the testing images should be more than 10. You can duplicate that testing image. Or you can rewrite your own function for testing

**Comment by NirvanaFY** [comment]
thanks for your reply . I use the FG to test ,and the image is more than 10 .I put the FG folder in the data,is that ok?
you said I can rewrite the function for testing .which model should I modify?
Im sorry that its my first time to use python and tensorflow,I hope you can tell me a little more in detail .
thank you !

**Comment by NirvanaFY** [comment]
I have solved .thank you !

**Comment by shz1314** [comment]
@susanqq @ZZUTK 
I have a good result in old version when training.But when testing, the result is bad. Do you have the test weight?
