### ISSUE TITLE
ValueError: Variable E_conv0/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope? 

### ISSUE THREAD

**Issue by PHPerWu** [ZZUTK/Face-Aging-CAAE#4]
I run the train code , but in # optimizer for discriminator on image
        self.D_img_optimizer = tf.train.AdamOptimizer(
            learning_rate=EG_learning_rate,
            beta1=beta1
        ).minimize(
            loss=self.loss_Di,
            var_list=self.D_img_variables
        )
tell me ValueError: Variable E_conv0/w/Adam/ does not exist
how should I do ?

**Comment by ZZUTK** [comment]
Which version of Tensorflow are you using? The demo code is tested on r0.12. If you are working with r1.0, it may report this error. I'm quite sure about this issue because I have not started to work on r1.0. You may try other optimizers, e.g., GradientDescentOptimizer.

**Comment by ZZUTK** [comment]
Someone asked the similar issue, please refer to 
https://github.com/carpedm20/DCGAN-tensorflow/issues/66
